Update WebSocketServer.js
TypeError: Cannot set property url of #<WebSocket> which has only a getter.
Seems that WebSocket use the `url` field and make it readonly.